In [1]:
# Check if on Colab and mount Drive
COLAB = False
try:
    from google import colab
    COLAB = True
except:
    pass

if COLAB:
    from google.colab import drive, userdata
    drive.mount('/content/drive')

REPO_PATH = '/content/drive/MyDrive/ep_populism_classification' if COLAB else str(Path("../../").resolve())

import sys
sys.path.append(REPO_PATH)

# Git config and pull latest
if COLAB:
    token = userdata.get('GITHUB_TOKEN')
    username = "gransera"
    repo = "ep_populism_classification"

    !git -C {REPO_PATH} config user.email "antonia.granser@gmail.com"
    !git -C {REPO_PATH} config user.name "Antonia Granser"
    !git -C {REPO_PATH} remote set-url origin https://{username}:{token}@github.com/{username}/{repo}.git
    !git -C {REPO_PATH} pull origin main

print("✓ Ready")

Mounted at /content/drive
From https://github.com/gransera/ep_populism_classification
 * branch            main       -> FETCH_HEAD
Already up to date.
✓ Ready

## Set up

### Import packages

In [ ]:
 # install required packages
!pip install -q seqeval~=1.2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done

In [2]:
from pathlib import Path
import pandas as pd

from sklearn.model_selection import train_test_split

import torch
from datasets import Dataset
from transformers import (
    set_seed,
    AutoTokenizer,
    DataCollatorWithPadding,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

In [3]:
# check which device is available
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
device

device(type='cuda')

In [4]:
SEED = 42
set_seed(SEED)

In [5]:
MODEL_NAME = "FacebookAI/roberta-base"

In [6]:
base_path = Path("/content/drive/MyDrive/ep_populism_classification/" if COLAB else "../../")
data_path = base_path / "data/annotations"

## Load and prepare data

### Load annotated data

In [7]:
annotations = pd.read_csv(data_path / "annotations.csv")
annotations.head()

,unique_id,speech_id,sentence_id,speaker,party,date,agenda,period,year,sentence,anti-elitism,people-centrism,populist
0,27_2,27,2,Jean-Lin Lacapelle,ID,2024-04-25,3. Pre-enlargement reforms and policy reviews ...,9,2024,"Firstly, we do not want a revision of the trea...",0,1,0
1,304_1,304,1,Mick Wallace,The Left,2024-04-24,17. La Hulpe declaration on the future of soci...,9,2024,"Mr President, ordinary people across Europe ar...",0,1,0
2,573_8,573,8,Younous Omarjee,The Left,2024-04-23,10. EU’s response to the repeated killing of h...,9,2024,"I believe they are, and I believe that today t...",0,1,0
3,3018_7,3018,7,Angelo Ciocca,ID,2024-02-26,15. European Central Bank – annual report 2023...,9,2024,"And so, President Lagarde, the criminal polici...",0,1,0
4,3101_6,3101,6,Clare Daly,The Left,2024-02-26,18. Tackling the inflation in food prices and ...,9,2024,"Ordinary people are caught in the vice, being ...",0,1,0

In [8]:
# Exctract relevant data on anti-elitism

elite_df = annotations[['unique_id', 'speech_id', 'sentence_id', 'sentence', 'anti-elitism']]

elite_df = elite_df.rename(columns={'anti-elitism': 'label'})

In [9]:
elite_df.head()

,unique_id,speech_id,sentence_id,sentence,label
0,27_2,27,2,"Firstly, we do not want a revision of the trea...",0
1,304_1,304,1,"Mr President, ordinary people across Europe ar...",0
2,573_8,573,8,"I believe they are, and I believe that today t...",0
3,3018_7,3018,7,"And so, President Lagarde, the criminal polici...",0
4,3101_6,3101,6,"Ordinary people are caught in the vice, being ...",0

In [10]:
len(elite_df)

2821

### Split df into train/dev/test set (70/15/15)

In [11]:
# Define function
def split_data(
    data: pd.DataFrame,
    test_size: float = 0.15,
    dev_size: float = 0.15,
    seed: int = 42,
):

# Split of test set
    train_dev, test = train_test_split(
        data, test_size=test_size, random_state=seed, stratify=data['label']
    )

# Split of dev set from remaining df
    train, dev = train_test_split(
        train_dev, test_size=dev_size / (1 - test_size), random_state=seed, stratify=train_dev['label']
    )

# Return the three datasets
    return train, dev, test

train, dev, test = split_data(elite_df, seed=SEED)

In [12]:
print(train['label'].value_counts())

label
0    1605
1     369
Name: count, dtype: int64

In [13]:
print(train['label'].value_counts(normalize=True))

label
0    0.81307
1    0.18693
Name: proportion, dtype: float64

### Convert dataframe to dataset objects

In [14]:
def create_dataset(df: pd.DataFrame) -> Dataset:
    return Dataset.from_pandas(df[['sentence', 'label']])

In [15]:
train_dataset = create_dataset(train)
dev_dataset = create_dataset(dev)
test_dataset = create_dataset(test)

### Tokenization of training data

In [16]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

def tokenize(batch):
    return tokenizer(batch['sentence'], truncation=True, padding=True, max_length=512)

train_dataset = train_dataset.map(tokenize, batched=True)
dev_dataset = dev_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/1974 [00:00<?, ? examples/s]

Map:   0%|          | 0/423 [00:00<?, ? examples/s]

Map:   0%|          | 0/424 [00:00<?, ? examples/s]

In [17]:
# verify tokenization looks right
print(train_dataset[0])
print(tokenizer.convert_ids_to_tokens(train_dataset[0]['input_ids']))

{'sentence': 'There also needs to be rejection and condemnation of any attempt to exploit the tragedy of the Haitian people by military occupation of their country, along with the unequivocal defence of Haiti’s sovereignty and independence – something that is missing from the document in question.', 'label': 0, '__index_level_0__': 1046, 'input_ids': [0, 970, 67, 782, 7, 28, 16117, 8, 19973, 9, 143, 2120, 7, 14958, 5, 6906, 9, 5, 32935, 82, 30, 831, 14349, 9, 49, 247, 6, 552, 19, 5, 39754, 21103, 2994, 9, 17009, 17, 27, 29, 13617, 8, 5201, 126, 402, 14, 16, 1716, 31, 5, 3780, 11, 864, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
['<s>', 'There', 'Ġalso', 'Ġneeds', 'Ġto', 'Ġbe', 'Ġrejection', 'Ġand', 'Ġcondemnation', 'Ġof', 'Ġany', 'Ġattempt', 'Ġto', 'Ġexploit', 'Ġthe', 'Ġtragedy', 'Ġof', 'Ġthe', 'ĠHaitian', 'Ġpeople', 'Ġby', 'Ġmilitary', 'Ġoccupation', 'Ġof', 'Ġtheir', 'Ġcountry', ',', 'Ġalong', 'Ġwith', 'Ġthe', 'Ġunequiv', 'ocal', 'Ġdefence', 'Ġof', 'ĠHaiti', 'âĢ', 'Ļ', 's', 'Ġsovereignty', 'Ġand', 'Ġindependence', 'ĠâĢĵ', 'Ġsomething', 'Ġthat', 'Ġis', 'Ġmissing', 'Ġfrom', 'Ġthe', 'Ġdocument', 'Ġin', 'Ġquestion', '.', '</s>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']

## Prepare for finetuning with 'TRAINER'

In [18]:
# Function to instantiate a fine-tunable sequence classification model

def model_init():
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
    model.config.problem_type = 'single_label_classification'
    return model

In [19]:
# Function to evaluate predicted against observed labels

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, matthews_corrcoef
import numpy as np
from scipy.special import softmax

THRESHOLD = 0.5  # first try

def compute_metrics(p):
    probs = softmax(p.predictions, axis=1)
    predictions = (probs[:, 1] >= THRESHOLD).astype(int)
    labels = p.label_ids
    return {
        'accuracy': accuracy_score(labels, predictions),
        'f1_macro': f1_score(labels, predictions, average='macro'),
        'f1_class1': f1_score(labels, predictions, average='binary'),
        'precision': precision_score(labels, predictions),
        'recall_class1': recall_score(labels, predictions),
        'recall': recall_score(labels, predictions),
        'mcc': matthews_corrcoef(labels, predictions),
    }

In [ ]:
!git -C {REPO_PATH} add .
!git -C {REPO_PATH} commit -m "Adapt computation of metrics to high class imbalance"
!git -C {REPO_PATH} push origin main

### Define training arguments

In [ ]:
# Create path to save model
model_folder = base_path / "models" / "classifiers" / "anti_elitism"
model_folder.mkdir(parents=True, exist_ok=True)

In [ ]:
# path to folder where model checkpoints and finetuning logs will be saved
training_args = TrainingArguments(
    output_dir=model_folder,
    logging_dir=model_folder / 'logs',
    # hyperparameters
    num_train_epochs=5,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=1,
    per_device_eval_batch_size=32,
    optim='adamw_torch',
    learning_rate=1e-5, # reduce for RoBERTa
    fp16=str(device).startswith('cuda'),
    # evaluation on dev set
    eval_strategy='epoch',
    # model saving
    metric_for_best_model='f1', # use 'f1_macro' for multiclass classification
    greater_is_better=True,
    save_strategy='epoch',
    load_best_model_at_end=True,
    save_total_limit=2,
    # logging
    logging_strategy='epoch',
    # for reproducibility
    seed=SEED,
    data_seed=SEED,
    full_determinism=True,
    # turn off logging to wandb or other backends
    report_to="none"
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [ ]:
from transformers import EarlyStoppingCallback

callbacks = [EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.02)]

### Include class balance function

In [ ]:
from torch.nn import CrossEntropyLoss
import torch

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        weights = torch.tensor([0.19, 0.81]).to(logits.device)
        loss_fn = CrossEntropyLoss(weight=weights)
        loss = loss_fn(logits, labels)
        return (loss, outputs) if return_outputs else loss

trainer = WeightedTrainer(
    model_init=model_init,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics,
    processing_class=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer),
    callbacks=callbacks
)

In [ ]:
# Create trainer

trainer = WeightedTrainer(
    model_init=model_init,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics,
    processing_class=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer),
    callbacks=callbacks
)

In [ ]:
"""
# Create trainer

trainer = Trainer(
    model_init=model_init,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics,
    processing_class=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer),
    callbacks=callbacks
)
"""

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## **Fine-tune**

In [ ]:
trainer.train() # min

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: FacebookAI/xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

### Test model on unseen test data

In [ ]:
# Model evaluation

test_model = trainer.evaluate(test_dataset, metric_key_prefix='test')
pd.Series(test_model)

early stopping required metric_for_best_model, but did not find eval_f1 so early stopping is disabled

test_loss                    0.614288
test_accuracy                0.879717
test_f1                      0.648276
test_precision               0.712121
test_recall                  0.594937
test_runtime                 1.702900
test_samples_per_second    248.982000
test_steps_per_second        8.221000
epoch                        6.000000
dtype: float64

### Performance checks

In [ ]:
print(train['label'].value_counts(normalize=True))

label
0    0.81307
1    0.18693
Name: proportion, dtype: float64

### Save model & tokenizer

In [ ]:
model_path = base_path / "models" / "classifiers"
model_folder = model_path / "anti_elitism" / "anti_elitism_xml_roberta_base_e3"
model_folder.mkdir(parents=True, exist_ok=True)

In [ ]:
# remove checkpoints and logs
import shutil
shutil.rmtree(model_folder)

In [ ]:
model_folder.mkdir(parents=True, exist_ok=True)
trainer.save_model(model_folder)

for item in model_folder.parent.iterdir():
    if item.name.startswith("checkpoint-"):
        shutil.rmtree(item)

tokenizer.save_pretrained(model_folder)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('/content/drive/MyDrive/ep_populism_classification/models/classifiers/anti_elitism/anti_elitism_xml_roberta_base_e3/tokenizer_config.json',
 '/content/drive/MyDrive/ep_populism_classification/models/classifiers/anti_elitism/anti_elitism_xml_roberta_base_e3/tokenizer.json')

In [ ]:
# delete
trainer.model.cpu()
del trainer
import gc; gc.collect();

### Synchronize with Git

In [ ]:
!git -C {REPO_PATH} add .
!git -C {REPO_PATH} commit -m "Add anti-elitism classifier (xml-roberta-base) results"
!git -C {REPO_PATH} push origin main

[main 75a5ece] Add anti-elitism classifier (xml-roberta-base) results
 2 files changed, 2 insertions(+), 1 deletion(-)
 create mode 100644 notebooks/01_training_elite_xmlRoBERTabase.ipynb
 rewrite notebooks/01_training_populism_BERTbase.ipynb (77%)
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 28.43 KiB | 1.29 MiB/s, done.
Total 5 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/gransera/ep_populism_classification.git
   fb16bbf..75a5ece  main -> main