In [1]:
# Check if on Colab and mount Drive
COLAB = False
try:
    from google import colab
    COLAB = True
except:
    pass

if COLAB:
    from google.colab import drive, userdata
    drive.mount('/content/drive')

# Set paths
REPO_PATH = '/content/drive/MyDrive/ep_populism_classification'
import sys
sys.path.append(REPO_PATH)

# Git config and pull latest
if COLAB:
    token = userdata.get('GITHUB_TOKEN')
    username = "gransera"
    repo = "ep_populism_classification"

    !git -C {REPO_PATH} config user.email "antonia.granser@gmail.com"
    !git -C {REPO_PATH} config user.name "Antonia Granser"
    !git -C {REPO_PATH} remote set-url origin https://{username}:{token}@github.com/{username}/{repo}.git
    !git -C {REPO_PATH} pull origin main

print("✓ Ready")

Mounted at /content/drive
fatal: not in a git directory
fatal: not in a git directory
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
✓ Ready

## Set up

### Import packages

In [2]:
 # install required packages
!pip install -q seqeval~=1.2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done

In [3]:
from pathlib import Path
import pandas as pd

from sklearn.model_selection import train_test_split

import torch
from datasets import Dataset
from transformers import (
    set_seed,
    AutoTokenizer,
    DataCollatorWithPadding,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

In [ ]:
"""
from src.utils.io import read_tabular
from src.finetuning import (
    split_data,
    create_sequence_classification_dataset,
    preprocess_sequence_classification_dataset
)

from src.metrics import (
    parse_sequence_classifier_prediction_output,
    compute_sequence_classification_metrics_binary
)
"""

In [4]:
# check which device is available
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
device

device(type='cuda')

In [5]:
SEED = 42
set_seed(SEED)

In [6]:
MODEL_NAME = "google-bert/bert-base-uncased"

In [7]:
base_path = Path("/content/drive/MyDrive/populism_classification/" if COLAB else "../../")
data_path = base_path / "data/annotations"

## Load and prepare data

### Load annotated data

In [8]:
annotations = pd.read_csv(data_path / "annotations.csv")
annotations.head()

,unique_id,speech_id,sentence_id,speaker,party,date,agenda,period,year,sentence,anti-elitism,people-centrism,populist
0,27_2,27,2,Jean-Lin Lacapelle,ID,2024-04-25,3. Pre-enlargement reforms and policy reviews ...,9,2024,"Firstly, we do not want a revision of the trea...",0,1,0
1,304_1,304,1,Mick Wallace,The Left,2024-04-24,17. La Hulpe declaration on the future of soci...,9,2024,"Mr President, ordinary people across Europe ar...",0,1,0
2,573_8,573,8,Younous Omarjee,The Left,2024-04-23,10. EU’s response to the repeated killing of h...,9,2024,"I believe they are, and I believe that today t...",0,1,0
3,3018_7,3018,7,Angelo Ciocca,ID,2024-02-26,15. European Central Bank – annual report 2023...,9,2024,"And so, President Lagarde, the criminal polici...",0,1,0
4,3101_6,3101,6,Clare Daly,The Left,2024-02-26,18. Tackling the inflation in food prices and ...,9,2024,"Ordinary people are caught in the vice, being ...",0,1,0

In [12]:
# Exctract relevant data on people-centrism

people_df = annotations[['unique_id', 'speech_id', 'sentence_id', 'sentence', 'people-centrism']]

people_df = people_df.rename(columns={'people-centrism': 'label'})

In [13]:
people_df.head()

,unique_id,speech_id,sentence_id,sentence,label
0,27_2,27,2,"Firstly, we do not want a revision of the trea...",1
1,304_1,304,1,"Mr President, ordinary people across Europe ar...",1
2,573_8,573,8,"I believe they are, and I believe that today t...",1
3,3018_7,3018,7,"And so, President Lagarde, the criminal polici...",1
4,3101_6,3101,6,"Ordinary people are caught in the vice, being ...",1

In [14]:
len(people_df)

2821

### Split df into train/dev/test set (70/15/15)

In [15]:
# Define function
def split_data(
    data: pd.DataFrame,
    test_size: float = 0.15,
    dev_size: float = 0.15,
    seed: int = 42,
):

# Split of test set
    train_dev, test = train_test_split(
        data, test_size=test_size, random_state=seed, stratify=data['label']
    )

# Split of dev set from remaining df
    train, dev = train_test_split(
        train_dev, test_size=dev_size / (1 - test_size), random_state=seed, stratify=train_dev['label']
    )

# Return the three datasets
    return train, dev, test

train, dev, test = split_data(people_df, seed=SEED)

In [ ]:
# create a dev and train split from the original train set
#data_splits = split_data(df, dev_size=0.15, test_size=0.15, seed=SEED, stratify_by='label', return_dict=True)

### Convert dataframe to dataset objects

In [20]:
def create_dataset(df: pd.DataFrame) -> Dataset:
    return Dataset.from_pandas(df[['sentence', 'label']])

In [21]:
train_dataset = create_dataset(train)
dev_dataset = create_dataset(dev)
test_dataset = create_dataset(test)

### Tokenization of training data

In [22]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

def tokenize(batch):
    return tokenizer(batch['sentence'], truncation=True, padding=True, max_length=512)

train_dataset = train_dataset.map(tokenize, batched=True)
dev_dataset = dev_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/1974 [00:00<?, ? examples/s]

Map:   0%|          | 0/423 [00:00<?, ? examples/s]

Map:   0%|          | 0/424 [00:00<?, ? examples/s]

In [23]:
# verify tokenization looks right
print(train_dataset[0])
print(tokenizer.convert_ids_to_tokens(train_dataset[0]['input_ids']))

{'sentence': 'If, instead of this, it accedes to cuts in the social area, along with relief for banks and the most wealthy, then no positive impulse can be expected, especially if there is an insistence on abstract criteria of financial stability.', 'label': 0, '__index_level_0__': 1064, 'input_ids': [101, 2065, 1010, 2612, 1997, 2023, 1010, 2009, 16222, 18352, 2000, 7659, 1999, 1996, 2591, 2181, 1010, 2247, 2007, 4335, 2005, 5085, 1998, 1996, 2087, 7272, 1010, 2059, 2053, 3893, 14982, 2064, 2022, 3517, 1010, 2926, 2065, 2045, 2003, 2019, 20616, 2006, 10061, 9181, 1997, 3361, 9211, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
['[CLS]', 'if', ',', 'instead', 'of', 'this', ',', 'it', 'acc', '##edes', 'to', 'cuts', 'in', 'the', 'social', 'area', ',', 'along', 'with', 'relief', 'for', 'banks', 'and', 'the', 'most', 'wealthy', ',', 'then', 'no', 'positive', 'impulse', 'can', 'be', 'expected', ',', 'especially', 'if', 'there', 'is', 'an', 'insistence', 'on', 'abstract', 'criteria', 'of', 'financial', 'stability', '.', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']

## Prepare for finetuning with 'TRAINER'

In [24]:
# Function to instantiate a fine-tunable sequence classification model

def model_init():
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
    model.config.problem_type = 'single_label_classification'
    return model

In [25]:
# Function to evaluate predicted against observed labels

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import numpy as np
from scipy.special import softmax

def compute_metrics(p):
    probs = softmax(p.predictions, axis=1)
    predictions = (probs[:, 1] >= 0.5).astype(int)
    labels = p.label_ids
    return {
        'accuracy': accuracy_score(labels, predictions),
        'f1': f1_score(labels, predictions),
        'precision': precision_score(labels, predictions),
        'recall': recall_score(labels, predictions)
    }

### Define training arguments

In [26]:
# Create path to save model
model_folder = base_path / "models" / "classifiers" / "people_centrism"
model_folder.mkdir(parents=True, exist_ok=True)

In [27]:
# path to folder where model checkpoints and finetuning logs will be saved
training_args = TrainingArguments(
    output_dir=model_folder,
    logging_dir=model_folder / 'logs',
    # hyperparameters
    num_train_epochs=10,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=1,
    per_device_eval_batch_size=32,
    optim='adamw_torch',
    fp16=str(device).startswith('cuda'),
    # evaluation on dev set
    eval_strategy='epoch',
    # model saving
    metric_for_best_model='f1', # use 'f1_macro' for multiclass classification
    greater_is_better=True,
    save_strategy='epoch',
    load_best_model_at_end=True,
    save_total_limit=2,
    # logging
    logging_strategy='epoch',
    # for reproducibility
    seed=SEED,
    data_seed=SEED,
    full_determinism=True,
    # turn off logging to wandb or other backends
    report_to="none"
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [28]:
from transformers import EarlyStoppingCallback

callbacks = [EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.02)]

In [30]:
# Create trainer

trainer = Trainer(
    model_init=model_init,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics,
    processing_class=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer),
    callbacks=callbacks
)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## **Fine-tune**

In [31]:
trainer.train()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=744, training_loss=0.1446378929640657, metrics={'train_runtime': 268.1216, 'train_samples_per_second': 73.623, 'train_steps_per_second': 4.625, 'total_flos': 1375400708563680.0, 'train_loss': 0.1446378929640657, 'epoch': 6.0})

### Test model on unseen test data

In [32]:
# Model evaluation

test_model = trainer.evaluate(test_dataset, metric_key_prefix='test')
pd.Series(test_model)

early stopping required metric_for_best_model, but did not find eval_f1 so early stopping is disabled

test_loss                    0.516590
test_accuracy                0.860849
test_f1                      0.646707
test_precision               0.620690
test_recall                  0.675000
test_runtime                 1.940800
test_samples_per_second    218.466000
test_steps_per_second        7.214000
epoch                        6.000000
dtype: float64

### Clone to git

In [35]:
!git -C {REPO_PATH} pull origin main

From https://github.com/gransera/populism_classification
 * branch            main       -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

In [36]:
!git -C {REPO_PATH} pull --no-rebase origin main

From https://github.com/gransera/populism_classification
 * branch            main       -> FETCH_HEAD
fatal: refusing to merge unrelated histories

In [37]:
!git -C {REPO_PATH} pull --no-rebase --allow-unrelated-histories origin main

From https://github.com/gransera/populism_classification
 * branch            main       -> FETCH_HEAD
Auto-merging .gitignore
CONFLICT (add/add): Merge conflict in .gitignore
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.

In [38]:
!git -C {REPO_PATH} commit --no-edit

U	.gitignore
U	README.md
error: Committing is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

In [39]:
!git -C {REPO_PATH} checkout --theirs .gitignore
!git -C {REPO_PATH} checkout --theirs README.md
!git -C {REPO_PATH} add .gitignore README.md
!git -C {REPO_PATH} commit --no-edit
!git -C {REPO_PATH} push origin main

Updated 1 path from the index
Updated 1 path from the index
[main 68aff90] Merge branch 'main' of https://github.com/gransera/populism_classification
Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 2 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (14/14), 5.74 KiB | 61.00 KiB/s, done.
Total 14 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), done.
To https://github.com/gransera/populism_classification.git
   b7d5b92..68aff90  main -> main

In [40]:
!git -C {REPO_PATH} add .
!git -C {REPO_PATH} commit -m "Add BERT fine-tuning pipeline for people-centrism classification"
!git -C {REPO_PATH} push origin main

error: invalid object 100644 974f5b1b2ac7c18cb848bc2c6e23fb0606f396ca for 'models/classifiers/people_centrism/checkpoint-372/optimizer.pt'
error: invalid object 100644 974f5b1b2ac7c18cb848bc2c6e23fb0606f396ca for 'models/classifiers/people_centrism/checkpoint-372/optimizer.pt'
error: Error building trees
Everything up-to-date

In [41]:
%%writefile {REPO_PATH}/.gitignore
models/
*.pt
*.bin
*.safetensors

Overwriting /content/drive/MyDrive/populism_classification/.gitignore

In [42]:
!git -C {REPO_PATH} rm -r --cached models/
!git -C {REPO_PATH} add .gitignore
!git -C {REPO_PATH} commit -m "Remove model checkpoints from tracking"
!git -C {REPO_PATH} push origin main

error: the following files have staged content different from both the
file and the HEAD:
    models/classifiers/people_centrism/checkpoint-372/config.json
    models/classifiers/people_centrism/checkpoint-372/model.safetensors
    models/classifiers/people_centrism/checkpoint-372/optimizer.pt
    models/classifiers/people_centrism/checkpoint-372/rng_state.pth
    models/classifiers/people_centrism/checkpoint-372/scaler.pt
    models/classifiers/people_centrism/checkpoint-372/scheduler.pt
    models/classifiers/people_centrism/checkpoint-372/tokenizer.json
    models/classifiers/people_centrism/checkpoint-372/tokenizer_config.json
    models/classifiers/people_centrism/checkpoint-372/trainer_state.json
    models/classifiers/people_centrism/checkpoint-372/training_args.bin
    models/classifiers/people_centrism/checkpoint-744/config.json
    models/classifiers/people_centrism/checkpoint-744/model.safetensors
    models/classifiers/people_centrism/checkpoint-744/optimizer.pt
    models/classifiers/people_centrism/checkpoint-744/rng_state.pth
    models/classifiers/people_centrism/checkpoint-744/scaler.pt
    models/classifiers/people_centrism/checkpoint-744/scheduler.pt
    models/classifiers/people_centrism/checkpoint-744/tokenizer.json
    models/classifiers/people_centrism/checkpoint-744/tokenizer_config.json
    models/classifiers/people_centrism/checkpoint-744/trainer_state.json
    models/classifiers/people_centrism/checkpoint-744/training_args.bin
(use -f to force removal)
error: invalid object 100644 974f5b1b2ac7c18cb848bc2c6e23fb0606f396ca for 'models/classifiers/people_centrism/checkpoint-372/optimizer.pt'
error: invalid object 100644 974f5b1b2ac7c18cb848bc2c6e23fb0606f396ca for 'models/classifiers/people_centrism/checkpoint-372/optimizer.pt'
error: Error building trees
Everything up-to-date