In [1]:
# Check if on Colab and mount Drive
COLAB = False
try:
    from google import colab
    COLAB = True
except:
    pass

if COLAB:
    from google.colab import drive, userdata
    drive.mount('/content/drive')

# Set paths
REPO_PATH = '/content/drive/MyDrive/ep_populism_classification'
import sys
sys.path.append(REPO_PATH)

# Git config and pull latest
if COLAB:
    token = userdata.get('GITHUB_TOKEN')
    username = "gransera"
    repo = "ep_populism_classification"

    !git -C {REPO_PATH} config user.email "antonia.granser@gmail.com"
    !git -C {REPO_PATH} config user.name "Antonia Granser"
    !git -C {REPO_PATH} remote set-url origin https://{username}:{token}@github.com/{username}/{repo}.git
    !git -C {REPO_PATH} pull origin main

print("✓ Ready")

Mounted at /content/drive
From https://github.com/gransera/ep_populism_classification
 * branch            main       -> FETCH_HEAD
Already up to date.
✓ Ready

## Set up

### Import packages

In [2]:
 # install required packages
!pip install -q seqeval~=1.2.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done

In [3]:
from pathlib import Path
import pandas as pd

from sklearn.model_selection import train_test_split

import torch
from datasets import Dataset
from transformers import (
    set_seed,
    AutoTokenizer,
    DataCollatorWithPadding,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

In [4]:
# check which device is available
device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
device

device(type='cuda')

In [5]:
SEED = 42
set_seed(SEED)

In [6]:
MODEL_NAME = "google-bert/bert-base-uncased"

In [12]:
base_path = Path("/content/drive/MyDrive/ep_populism_classification/" if COLAB else "../../")
data_path = base_path / "data/annotations"

## Load and prepare data

### Load annotated data

In [13]:
annotations = pd.read_csv(data_path / "annotations.csv")
annotations.head()

,unique_id,speech_id,sentence_id,speaker,party,date,agenda,period,year,sentence,anti-elitism,people-centrism,populist
0,27_2,27,2,Jean-Lin Lacapelle,ID,2024-04-25,3. Pre-enlargement reforms and policy reviews ...,9,2024,"Firstly, we do not want a revision of the trea...",0,1,0
1,304_1,304,1,Mick Wallace,The Left,2024-04-24,17. La Hulpe declaration on the future of soci...,9,2024,"Mr President, ordinary people across Europe ar...",0,1,0
2,573_8,573,8,Younous Omarjee,The Left,2024-04-23,10. EU’s response to the repeated killing of h...,9,2024,"I believe they are, and I believe that today t...",0,1,0
3,3018_7,3018,7,Angelo Ciocca,ID,2024-02-26,15. European Central Bank – annual report 2023...,9,2024,"And so, President Lagarde, the criminal polici...",0,1,0
4,3101_6,3101,6,Clare Daly,The Left,2024-02-26,18. Tackling the inflation in food prices and ...,9,2024,"Ordinary people are caught in the vice, being ...",0,1,0

In [14]:
# Exctract relevant data on people-centrism

people_df = annotations[['unique_id', 'speech_id', 'sentence_id', 'sentence', 'people-centrism']]

people_df = people_df.rename(columns={'people-centrism': 'label'})

In [15]:
people_df.head()

,unique_id,speech_id,sentence_id,sentence,label
0,27_2,27,2,"Firstly, we do not want a revision of the trea...",1
1,304_1,304,1,"Mr President, ordinary people across Europe ar...",1
2,573_8,573,8,"I believe they are, and I believe that today t...",1
3,3018_7,3018,7,"And so, President Lagarde, the criminal polici...",1
4,3101_6,3101,6,"Ordinary people are caught in the vice, being ...",1

In [16]:
len(people_df)

2821

### Split df into train/dev/test set (70/15/15)

In [17]:
# Define function
def split_data(
    data: pd.DataFrame,
    test_size: float = 0.15,
    dev_size: float = 0.15,
    seed: int = 42,
):

# Split of test set
    train_dev, test = train_test_split(
        data, test_size=test_size, random_state=seed, stratify=data['label']
    )

# Split of dev set from remaining df
    train, dev = train_test_split(
        train_dev, test_size=dev_size / (1 - test_size), random_state=seed, stratify=train_dev['label']
    )

# Return the three datasets
    return train, dev, test

train, dev, test = split_data(people_df, seed=SEED)

### Convert dataframe to dataset objects

In [18]:
def create_dataset(df: pd.DataFrame) -> Dataset:
    return Dataset.from_pandas(df[['sentence', 'label']])

In [19]:
train_dataset = create_dataset(train)
dev_dataset = create_dataset(dev)
test_dataset = create_dataset(test)

### Tokenization of training data

In [20]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

def tokenize(batch):
    return tokenizer(batch['sentence'], truncation=True, padding=True, max_length=512)

train_dataset = train_dataset.map(tokenize, batched=True)
dev_dataset = dev_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/1974 [00:00<?, ? examples/s]

Map:   0%|          | 0/423 [00:00<?, ? examples/s]

Map:   0%|          | 0/424 [00:00<?, ? examples/s]

In [21]:
# verify tokenization looks right
print(train_dataset[0])
print(tokenizer.convert_ids_to_tokens(train_dataset[0]['input_ids']))

{'sentence': 'If, instead of this, it accedes to cuts in the social area, along with relief for banks and the most wealthy, then no positive impulse can be expected, especially if there is an insistence on abstract criteria of financial stability.', 'label': 0, '__index_level_0__': 1064, 'input_ids': [101, 2065, 1010, 2612, 1997, 2023, 1010, 2009, 16222, 18352, 2000, 7659, 1999, 1996, 2591, 2181, 1010, 2247, 2007, 4335, 2005, 5085, 1998, 1996, 2087, 7272, 1010, 2059, 2053, 3893, 14982, 2064, 2022, 3517, 1010, 2926, 2065, 2045, 2003, 2019, 20616, 2006, 10061, 9181, 1997, 3361, 9211, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
['[CLS]', 'if', ',', 'instead', 'of', 'this', ',', 'it', 'acc', '##edes', 'to', 'cuts', 'in', 'the', 'social', 'area', ',', 'along', 'with', 'relief', 'for', 'banks', 'and', 'the', 'most', 'wealthy', ',', 'then', 'no', 'positive', 'impulse', 'can', 'be', 'expected', ',', 'especially', 'if', 'there', 'is', 'an', 'insistence', 'on', 'abstract', 'criteria', 'of', 'financial', 'stability', '.', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']

## Prepare for finetuning with 'TRAINER'

In [22]:
# Function to instantiate a fine-tunable sequence classification model

def model_init():
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)
    model.config.problem_type = 'single_label_classification'
    return model

In [23]:
# Function to evaluate predicted against observed labels

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import numpy as np
from scipy.special import softmax

def compute_metrics(p):
    probs = softmax(p.predictions, axis=1)
    predictions = (probs[:, 1] >= 0.5).astype(int)
    labels = p.label_ids
    return {
        'accuracy': accuracy_score(labels, predictions),
        'f1': f1_score(labels, predictions),
        'precision': precision_score(labels, predictions),
        'recall': recall_score(labels, predictions)
    }

### Define training arguments

In [24]:
# Create path to save model
model_folder = base_path / "models" / "classifiers" / "people_centrism"
model_folder.mkdir(parents=True, exist_ok=True)

In [25]:
# path to folder where model checkpoints and finetuning logs will be saved
training_args = TrainingArguments(
    output_dir=model_folder,
    logging_dir=model_folder / 'logs',
    # hyperparameters
    num_train_epochs=10,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=1,
    per_device_eval_batch_size=32,
    optim='adamw_torch',
    fp16=str(device).startswith('cuda'),
    # evaluation on dev set
    eval_strategy='epoch',
    # model saving
    metric_for_best_model='f1', # use 'f1_macro' for multiclass classification
    greater_is_better=True,
    save_strategy='epoch',
    load_best_model_at_end=True,
    save_total_limit=2,
    # logging
    logging_strategy='epoch',
    # for reproducibility
    seed=SEED,
    data_seed=SEED,
    full_determinism=True,
    # turn off logging to wandb or other backends
    report_to="none"
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [26]:
from transformers import EarlyStoppingCallback

callbacks = [EarlyStoppingCallback(early_stopping_patience=3, early_stopping_threshold=0.02)]

In [27]:
# Create trainer

trainer = Trainer(
    model_init=model_init,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=dev_dataset,
    compute_metrics=compute_metrics,
    processing_class=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer),
    callbacks=callbacks
)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## **Fine-tune**

In [28]:
trainer.train()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: google-bert/bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=744, training_loss=0.1446378929640657, metrics={'train_runtime': 254.8856, 'train_samples_per_second': 77.447, 'train_steps_per_second': 4.865, 'total_flos': 1375400708563680.0, 'train_loss': 0.1446378929640657, 'epoch': 6.0})

### Test model on unseen test data

In [29]:
# Model evaluation

test_model = trainer.evaluate(test_dataset, metric_key_prefix='test')
pd.Series(test_model)

early stopping required metric_for_best_model, but did not find eval_f1 so early stopping is disabled

test_loss                    0.516590
test_accuracy                0.860849
test_f1                      0.646707
test_precision               0.620690
test_recall                  0.675000
test_runtime                 2.139600
test_samples_per_second    198.165000
test_steps_per_second        6.543000
epoch                        6.000000
dtype: float64

### Save model & tokenizer

In [ ]:
model_path = base_path / "models" / "classifiers"
model_folder = model_path / "people_centrism" / "people_centrism_bert_base_e3"
model_folder.mkdir(parents=True, exist_ok=True)

In [ ]:
# remove checkpoints and logs
import shutil
shutil.rmtree(model_folder)

In [ ]:
model_folder.mkdir(parents=True, exist_ok=True)
trainer.save_model(model_folder)
tokenizer.save_pretrained(model_folder)

In [ ]:
# delete
trainer.model.cpu()
del trainer
import gc; gc.collect();

### Synchronize with Git

In [ ]:
!git -C {REPO_PATH} add .
!git -C {REPO_PATH} commit -m "Add people-centrism classifier (bert-base-uncased) results"
!git -C {REPO_PATH} push origin main