In [2]:
# Check if on Colab and mount Drive
COLAB = False
try:
    from google import colab
    COLAB = True
except:
    pass

if COLAB:
    from google.colab import drive, userdata
    drive.mount('/content/drive')

REPO_PATH = '/content/drive/MyDrive/ep_populism_classification' if COLAB else str(Path("../../").resolve())

import sys
sys.path.append(REPO_PATH)

# Git config and pull latest
if COLAB:
    token = userdata.get('GITHUB_TOKEN')
    username = "gransera"
    repo = "ep_populism_classification"

    !git -C {REPO_PATH} config user.email "antonia.granser@gmail.com"
    !git -C {REPO_PATH} config user.name "Antonia Granser"
    !git -C {REPO_PATH} remote set-url origin https://{username}:{token}@github.com/{username}/{repo}.git
    !git -C {REPO_PATH} pull origin main

print("Ready")

Mounted at /content/drive
From https://github.com/gransera/ep_populism_classification
 * branch            main       -> FETCH_HEAD
Already up to date.
Ready

## Set up

In [3]:
from pathlib import Path

import pandas as pd
import numpy as np

from transformers import pipeline
from tqdm.notebook import tqdm

import torch

In [4]:
base_path     = Path("/content/drive/MyDrive/ep_populism_classification" if COLAB else "../../")
data_path     = base_path / "data/datasets"
model_path    = base_path / "models/classifiers"
output_folder = base_path / "outputs/predictions"

## Load data

In [5]:
# Load full dataset
df = pd.read_csv(data_path / "parllaw_preprocessed.csv")

# Drop the dictionary tokenization columns
df = df.drop(columns=['sentence_pre'])

print(len(df))
print(df.head(5))

4055401
  unique_id  speech_id  sentence_id        speaker       party        date  \
0       1_1          1            1  Daniel Freund  Greens/EFA  2024-04-25
1       1_2          1            2  Daniel Freund  Greens/EFA  2024-04-25
2       1_3          1            3  Daniel Freund  Greens/EFA  2024-04-25
3       1_4          1            4  Daniel Freund  Greens/EFA  2024-04-25
4       1_5          1            5  Daniel Freund  Greens/EFA  2024-04-25

                                              agenda  period  year  \
0  2. Interinstitutional Body for Ethical Standar...       9  2024
1  2. Interinstitutional Body for Ethical Standar...       9  2024
2  2. Interinstitutional Body for Ethical Standar...       9  2024
3  2. Interinstitutional Body for Ethical Standar...       9  2024
4  2. Interinstitutional Body for Ethical Standar...       9  2024

                                            sentence
0                  Madam President, dear colleagues!
1                     Politics must not be for sale.
2  It cannot be that political decisions in this ...
3  Whether Qatar, Russia, or China – especially w...
4  Even below the threshold of criminal law, belo...

## Load model

In [6]:
model_folder = model_path / "populism/populism_roberta_large_2_e2"

classifier = pipeline(
    task='text-classification',
    model=model_folder,
    device=0 if torch.cuda.is_available() else -1,
    top_k=None
)

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

### Settings

In [6]:
BATCH_SIZE   = 256
CHUNK_SIZE   = 9984
output_file  = output_folder / "populism_robertalarge_full_predictions.csv"

## Data inference

In [8]:
import torch
print(torch.cuda.get_device_name(0))

NVIDIA A100-SXM4-40GB

In [9]:
# Resume logic
if output_file.exists():
    done      = pd.read_csv(output_file)
    start_row = len(done)
    print(f"Resuming from row {start_row}/{len(df)}")
else:
    start_row = 0
    print(f"Starting fresh — {len(df)} rows total")


# Inference in chunks
for chunk_start in tqdm(range(start_row, len(df), CHUNK_SIZE), desc="Chunks"):
    chunk_end = min(chunk_start + CHUNK_SIZE, len(df))
    chunk     = df.iloc[chunk_start:chunk_end]

    preds = classifier(
          chunk['sentence'].tolist(),
          batch_size=BATCH_SIZE,
          truncation=True,
          max_length=512
    )

    chunk_df = pd.DataFrame({
      'unique_id':         chunk['unique_id'].values,
      'prob_non_populism':  [next(x['score'] for x in p if x['label'] == 'LABEL_0') for p in preds],
      'prob_populism': [next(x['score'] for x in p if x['label'] == 'LABEL_1') for p in preds],
    })

    # Append to CSV — header only on first write
    chunk_df.to_csv(output_file, mode='a', header=chunk_start == start_row == 0, index=False)

print(f"Done — results saved to {output_file}")

Resuming from row 99840/4055401

Chunks:   0%|          | 0/397 [00:00<?, ?it/s]

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Done — results saved to /content/drive/MyDrive/ep_populism_classification/outputs/predictions/populism_robertalarge_full_predictions.csv

## Reload results

In [7]:
# Load full results and apply threshold
preds_df = pd.read_csv(output_file)

In [8]:
preds_df.head()

  unique_id  prob_non_populism  prob_populism
0       1_1           0.995385       0.004615
1       1_2           0.989144       0.010856
2       1_3           0.969885       0.030115
3       1_4           0.993131       0.006869
4       1_5           0.993622       0.006378

In [9]:
# Check for duplicates
print(f"Total rows:      {len(preds_df)}")
print(f"Unique IDs:      {preds_df['unique_id'].nunique()}")
print(f"Duplicates:      {preds_df.duplicated(subset='unique_id').sum()}")

Total rows:      4043520
Unique IDs:      4043520
Duplicates:      0

In [19]:
# Apply best performing threshold

THRESHOLD = 0.563 # best macro F1
preds_df['populism_binary'] = (preds_df['prob_populism'] >= THRESHOLD).astype(int)
preds_df.head()

  unique_id  prob_non_populism  prob_populism  populism_binary
0       1_1           0.995385       0.004615                0
1       1_2           0.989144       0.010856                0
2       1_3           0.969885       0.030115                0
3       1_4           0.993131       0.006869                0
4       1_5           0.993622       0.006378                0

In [20]:
# Save file
preds_df.to_csv(output_folder / "populism_robertalarge_full_predictions_threshold.csv", index=False)

In [12]:
# Merge prediction df with original df
    # in fresh session necessary to load parllaw corpus again
df_final = df.merge(preds_df, on='unique_id')
df_final.head()

,unique_id,speech_id,sentence_id,speaker,party,date,agenda,period,year,sentence,prob_non_populism,prob_populism,populism_binary
0,1_1,1,1,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Madam President, dear colleagues!",0.995385,0.004615,0
1,1_2,1,2,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,Politics must not be for sale.,0.989144,0.010856,0
2,1_3,1,3,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,It cannot be that political decisions in this ...,0.969885,0.030115,0
3,1_4,1,4,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Whether Qatar, Russia, or China – especially w...",0.993131,0.006869,0
4,1_5,1,5,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Even below the threshold of criminal law, belo...",0.993622,0.006378,0

In [21]:
# Safe final file
df_final.to_csv(output_folder / "ep_speeches_populism.csv", index=False)

### Quick overview

In [13]:
df_final['populism_binary'].value_counts()

populism_binary
0    3979539
1      63981
Name: count, dtype: int64

In [14]:
df_final['populism_binary'].value_counts(normalize=True)

populism_binary
0    0.984177
1    0.015823
Name: proportion, dtype: float64

In [16]:
print(f"\nMax:  {df_final['prob_populism'].max()}")
print(f"Min:  {df_final['prob_populism'].min()}")
print(f"Mean: {df_final['prob_populism'].mean()}")

Max:  0.9990023970603944
Min:  0.0012428056215867
Mean: 0.022986749632726223

## Synchronize with Git

In [22]:
# Clear widget metadata before saving
from IPython.display import clear_output
clear_output()

In [ ]:
!git -C {REPO_PATH} add .
!git -C {REPO_PATH} commit -m "Inference of populism on full EP speech corpus"
!git -C {REPO_PATH} push origin main

In [ ]:
""" Clear widget meta data in terminal

cd /content/drive/MyDrive/ep_populism_classification
python -c "
import json

notebooks = [
    'notebooks/02_model_application_elite.ipynb',
]

for nb_path in notebooks:
    with open(nb_path, 'r') as f:
        nb = json.load(f)

    # Remove corrupted widget metadata
    if 'widgets' in nb.get('metadata', {}):
        del nb['metadata']['widgets']

    with open(nb_path, 'w') as f:
        json.dump(nb, f, indent=1)

    print(f'Fixed {nb_path}')
"